### PR TITLE
README: add build status table

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
Add build status table.
Signed-off-by: Tyler Baker <tyler.baker@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
Merging this, as it's trivial and has been reviewed by Michael.

**Pull request merged**
