### PR TITLE
CI: update urls to reflect new domain

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
We've switched to using https://ci.linarotechnologies.org so update the links to reflect this migration.

Signed-off-by: Tyler Baker <tyler.baker@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
Trivial change to the markdown, apply this with @mike-scott approval.

**Pull request merged**
