### PR TITLE
Relocate ROM images with new config option

### PR DESCRIPTION
**Pull request by mbolivar**
This pull request depends on:

https://github.com/mbolivar/zephyr/commit/8bf4af950fc96e060241b7186d0175b02a3f4d0f

The upstream review is at:

https://gerrit.zephyrproject.org/r/#/c/11109/

Using CONFIG_FLASH_LOAD_OFFSET instead of abusing CONFIG_FLASH_BASE_ADDRESS un-breaks the flash driver on Carbon.

Not safe to merge unless zephyr is updated to match.

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Failed.

**Comment by gatek33p3r** [comment]
Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Pull request merged**
