### PR TITLE
README: add dependencies page and link to it.

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
Add dependencies page to list the build statuses over our various software components.
Signed-off-by: Tyler Baker <tyler.baker@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by mike-scott** [comment]
Looks good to me :)

**Pull request merged**
