### PR TITLE
README: update link to point to LTD wiki

### PR DESCRIPTION
**Pull request by akbennettatlinaro**
Signed-off-by: Alan Bennett <alan.bennett@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
LGTM.

**Pull request merged**
