### PR TITLE
boot_utils: add error handling for flash commands

### PR DESCRIPTION
**Pull request by mike-scott**
Signed-off-by: Michael Scott <michael.scott@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by rsalveti** [comment]
LGTM, tested on Nitrogen.

**Pull request merged**
