### PR TITLE
fota: add Zephyr temp sensor handling

### PR DESCRIPTION
**Pull request by mike-scott**
This patch assumes that current temperature sensors will bring up
TEMP_0 device.  If this is not correct we can always diffentiate
the temp device names in device.h later.

Signed-off-by: Michael Scott <michael.scott@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Succeeded.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by mike-scott** [comment]
Dropping this so that @mbolivar can implement a thread for the temp sensor loop

**Pull request closed without merging**
