### PR TITLE
[Test] Just a test

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
Can ignore.
Signed-off-by: Tyler Baker <tyler.baker@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Failed.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Bootloader Build Failed.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Pull request closed without merging**
