### PR TITLE
Replace sys_arch_reboot with sys_reboot.

### PR DESCRIPTION
**Pull request by rsalveti**
sys_reboot takes care of disabling interrupts and sys_clock before
calling sys_arch_reboot.

Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
K64F Deployment Succeeded.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Pull request merged**
