### PR TITLE
dependencies: add zephyr build status table

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
Add zephyr build status table to dependencies page, to reflect current status in our dev repo and upstream.

Signed-off-by: Tyler Baker <tyler.baker@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by mike-scott** [comment]
LGTM -- But, was the Nitrogen build fail on purpose?

**Comment by EmbeddedAndroid** [comment]
I thought it was strange too, as it's building the tests/legacy/kernel/test_timer/microkernel/test fine upstream, just our dev branches is failing to build that test.

The gist is
`zephyr-ltd/PLATFORM/96b_nitrogen/drivers/spi/spi_nrf5_slave.c:129:24: error: suggest parentheses around '&&' within '||' [-Werror=parentheses]
  __ASSERT(!(tx_buf_len && !tx_buf  || rx_buf_len && !rx_buf),
cc1: all warnings being treated as errors`

Full log can be found here: https://ci.arm64.io/job/zephyr-ltd/PLATFORM=96b_nitrogen/2/console

**Comment by EmbeddedAndroid** [comment]
Looks like there is another build error:
`/home/jenkins/workspace/zephyr-ltd/PLATFORM/96b_nitrogen/drivers/spi/spi_nrf5_slave.c:248:32: error: 'CONFIG_GPIO_NRF5_P0_DEV_NAME' undeclared (first use in this function)
  gpio_dev = device_get_binding(CONFIG_GPIO_NRF5_P0_DEV_NAME);`

**Comment by EmbeddedAndroid** [comment]
The first error/warning is fixed with this PR - https://github.com/Linaro/zephyr/pull/4

**Pull request merged**
