### PR TITLE
Ignore cscope files.

### PR DESCRIPTION
**Pull request by mbolivar**

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Failed.

**Comment by rsalveti** [comment]
LGTM

**Pull request merged**
