### PR TITLE
[TEST] Add printk line over 80 char

### PR DESCRIPTION
**Pull request by EmbeddedAndroid**
Testing our CI bot.

Signed-off-by: Tyler Baker <tyler.baker@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
retest

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
${PLATFORM} Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
${PLATFORM} Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
${PLATFORM} Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
${PLATFORM} Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
${PLATFORM} Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
${PLATFORM} Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
${PLATFORM} Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Bootloader Build Failed.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Bootloader Build Failed.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Failed.

**Comment by EmbeddedAndroid** [comment]
rebuild

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Pull request closed without merging**
