### PR TITLE
README: Update link to point to LTD wiki

### PR DESCRIPTION
**Pull request by akbennettatlinaro**
Signed-off-by: Alan Bennett alan.bennett@linaro.org

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by akbennettatlinaro** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Pull request closed without merging**
