### PR TITLE
Stop advertising once the device is connected

### PR DESCRIPTION
**Pull request by rsalveti**
Assume the device will be controlled over IP once connected.

Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by rsalveti** [comment]
Looks like not every device is able to be properly connected with this change. I'm getting some weird behavior where the BT connection is in place, but not the 6lowpan part of it. Needs more testing.

**Comment by rsalveti** [comment]
Will drop this one for now, the new script will handle the devices that are already connected.

**Pull request closed without merging**
