### PR TITLE
NRF5 fixes and updates

### PR DESCRIPTION
**Pull request by mbolivar**
- Adjust Nitrogen flash layout to avoid breaking our boards too soon
- Add NRF52840-PDK support

*MUST BE MERGED TOGETHER WITH https://github.com/runtimeco/mcuboot/pull/27*

*THIS WILL BREAK ANY FLASHING SCRIPTS FOR NITROGEN* -- a documentation update PR is incoming.

Carbon and Nitrogen both OTA successfully with this series and the corresponding mcuboot pull. K64F sometimes does and sometimes gets stuck with networking issues.

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Comment by rsalveti** [comment]
LGTM, needs to be merged together with our mcuboot branch.

**Pull request merged**
