### PR TITLE
Rename default temperature sensor name to mcu_temp

### PR DESCRIPTION
**Pull request by rsalveti**
Name the internal (MCU) temperature sensor as 'mcu_temp', and use
'temperature' for the external temperature sensor (e.g. sensorhub).

Signed-off-by: Ricardo Salveti <ricardo.salveti@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Failed.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Failed.

**Comment by mbolivar** [comment]
LGTM

**Pull request merged**
