### PR TITLE
bt: always use product_id.number to create BT addr

### PR DESCRIPTION
**Pull request by mike-scott**
Now that product_id.number is (mostly) unique for all supported
devices, let's use that to create a (mostly) unique BT addr and
remove the device specific complexity from set_own_bt_addr()

Signed-off-by: Michael Scott <michael.scott@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by rsalveti** [comment]
LGTM

**Pull request merged**
