### PR TITLE
andy test

### PR DESCRIPTION
**Pull request by doanac**

### CODE REVIEW

**Comment by doanac** [comment]
ci-retest (need new jobdef for CONFIG_NET_APP_PEER_IPV4_ADDR)

**Comment by doanac** [comment]
ci-retest (need LAVA_USER defined)

**Comment by doanac** [comment]
ci-retest (github served cached version of project.yml)

**Comment by doanac** [comment]
ci-retest - fix ${DEVICE_TYPE} in definition

**Comment by doanac** [comment]
ci-retest (github cached again)

**Comment by doanac** [comment]
ci-retest

**Comment by doanac** [comment]
ci-retest (using wget with headers)

**Comment by doanac** [comment]
ci-retest (fix fake bug in build script).

**Comment by doanac** [comment]
ci-retest (moved testing to validation.linarotechnologies.org)

**Comment by doanac** [comment]
ci-retest (fixed loop-on bug in jobserv)

**Comment by doanac** [comment]
ci-retest - add JOB_NAME in project.yml

**Comment by doanac** [comment]
ci-retest (cached error in ghithub)

**Comment by doanac** [comment]
ci-retest fix bug in jobserv url for lava

**Comment by doanac** [comment]
ci-retest

**Comment by doanac** [comment]
ci-retest (pass LAVA_* all via secrets)

**Comment by doanac** [comment]
ci-retest (make lava runner smarter)

**Comment by doanac** [comment]
ci-retest more bugs

**Comment by doanac** [comment]
ci-retest (was a bad password!)

**Comment by doanac** [comment]
ci-retest (use signed image)

**Comment by doanac** [comment]
ci-retest - fix lava-submit script

**Comment by doanac** [comment]
ci-retest for real

**Comment by mbolivar** [comment]
This seems to have served its purpose, so I'm closing it. Please reopen if you're still using this :).

**Pull request closed without merging**
