### PR TITLE
bluetooth: change advertised beacon name once connected

### PR DESCRIPTION
**Pull request by mike-scott**
Once connected, the beacon name is changed to "Connected IPSP node".

This stops successive attempts to connect the IoT device by any nearby
gateways which won't be able to see that it is already connected.

Signed-off-by: Michael Scott <michael.scott@linaro.org>

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Failed.

**Comment by gatek33p3r** [comment]
K64F Deployment Succeeded.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Succeeded.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Failed.

**Comment by EmbeddedAndroid** [comment]
recheck

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by rsalveti** [comment]
It seems to only really work on Carbon, as on Nitrogen it basically stops the advertisement completely.

**Comment by mike-scott** [comment]
But if you do actually stop the advertisement it breaks IPv6 entirely.. so weird.

**Comment by rsalveti** [comment]
Just tested on both nitrogen and carbon, will merge as there is no bad side effect. Needs follow up to understand why it works differently on nitrogen.

**Pull request merged**
