### PR TITLE
Post-Connect fixups and integration

### PR DESCRIPTION
**Pull request by mbolivar**
This series:

- Fixes up some warnings and other issues introduced while we were in a hurry for the Connect demo
- Re-works the bluemix API to allow arbitrary JSON status to be posted
- Uses that to integrate work done by Maureen Helm upstream in Zephyr to add support for off-chip temperature devices such as the one found on the FRDM-K64F

The off-chip temperature support can also be used to integrate support for the sensor hub demonstrated at Connect, once that's cleaned up.

### CODE REVIEW

**Comment by gatek33p3r** [comment]
Checkpatch Suceeded.

**Comment by gatek33p3r** [comment]
Bootloader Build Succeeded.

**Comment by gatek33p3r** [comment]
Application Build Succeeded.

**Comment by gatek33p3r** [comment]
K64F Deployment Failed.

**Comment by gatek33p3r** [comment]
Nitrogen Deployment Succeeded.

**Comment by mbolivar** [comment]
Will resubmit on top of Kconfig (https://github.com/Linaro/zephyr-fota-hawkbit/pull/71)

**Pull request closed without merging**
